/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Airlines_system;

/**
 *
 * @author Afrotto
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date_day1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Date_day2 = new javax.swing.JComboBox<>();
        Date_day = new javax.swing.JComboBox<>();
        Date_month = new javax.swing.JComboBox<>();
        Date_year = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ready to hit the skies?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Source");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Destination");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 163, -1, -1));

        Date_day1.setForeground(new java.awt.Color(51, 51, 51));
        Date_day1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Egypt" }));
        Date_day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_day1ActionPerformed(evt);
            }
        });
        getContentPane().add(Date_day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, -1, -1));

        Date_day2.setForeground(new java.awt.Color(51, 51, 51));
        Date_day2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "United States (Washington)", "Saudi-Arabia (Riyadh)", "Germany (Berlin)", "Kuwait (Kuwait)", "United Arab Emirates (Abu Dhabi)", "Russia (Moscow)", "Lebanon (Beirut)" }));
        Date_day2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_day2ActionPerformed(evt);
            }
        });
        getContentPane().add(Date_day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 200, -1));

        Date_day.setForeground(new java.awt.Color(51, 51, 51));
        Date_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(Date_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 206, 50, -1));

        Date_month.setForeground(new java.awt.Color(51, 51, 51));
        Date_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Febraury", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(Date_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 206, 80, -1));

        Date_year.setForeground(new java.awt.Color(51, 51, 51));
        Date_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025" }));
        Date_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_yearActionPerformed(evt);
            }
        });
        getContentPane().add(Date_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 206, 60, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 80, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airlines_system/airplane-tickets-patch-airline-boarding-pass-documents-color-sticker-isolated-illustration-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Date_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_yearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reservation_final rf= new reservation_final();
        rf.setVisible(true);
        rf.pack();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Date_day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_day1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_day1ActionPerformed

    private void Date_day2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_day2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_day2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Date_day;
    private javax.swing.JComboBox<String> Date_day1;
    private javax.swing.JComboBox<String> Date_day2;
    private javax.swing.JComboBox<String> Date_month;
    private javax.swing.JComboBox<String> Date_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
